// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// RSAVS_LargeN_Rcpp
Rcpp::List RSAVS_LargeN_Rcpp(const Eigen::MatrixXd x_mat, const Eigen::VectorXd y_vec, const int n, const int p, const std::string& loss_type, const Eigen::VectorXd loss_param, const char p1_type, Eigen::VectorXd p1_param, const char p2_type, Eigen::VectorXd p2_param, const Eigen::VectorXd lam1_vec, const Eigen::VectorXd lam2_vec, const double r1, const double r2, const double r3, const double phi, const double tol, const double max_iter);
RcppExport SEXP _RSAVS_RSAVS_LargeN_Rcpp(SEXP x_matSEXP, SEXP y_vecSEXP, SEXP nSEXP, SEXP pSEXP, SEXP loss_typeSEXP, SEXP loss_paramSEXP, SEXP p1_typeSEXP, SEXP p1_paramSEXP, SEXP p2_typeSEXP, SEXP p2_paramSEXP, SEXP lam1_vecSEXP, SEXP lam2_vecSEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP r3SEXP, SEXP phiSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type loss_type(loss_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type loss_param(loss_paramSEXP);
    Rcpp::traits::input_parameter< const char >::type p1_type(p1_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type p1_param(p1_paramSEXP);
    Rcpp::traits::input_parameter< const char >::type p2_type(p2_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type p2_param(p2_paramSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type lam1_vec(lam1_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type lam2_vec(lam2_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< const double >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const double >::type r3(r3SEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(RSAVS_LargeN_Rcpp(x_mat, y_vec, n, p, loss_type, loss_param, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r1, r2, r3, phi, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// RSAVS_LargeN_L2_Rcpp
Rcpp::List RSAVS_LargeN_L2_Rcpp(const Eigen::MatrixXd x_mat, const Eigen::VectorXd y_vec, const int n, const int p, const char p1_type, Eigen::VectorXd p1_param, const char p2_type, Eigen::VectorXd p2_param, const Eigen::VectorXd lam1_vec, const Eigen::VectorXd lam2_vec, const double r2, const double r3, const double phi, const double tol, const double max_iter);
RcppExport SEXP _RSAVS_RSAVS_LargeN_L2_Rcpp(SEXP x_matSEXP, SEXP y_vecSEXP, SEXP nSEXP, SEXP pSEXP, SEXP p1_typeSEXP, SEXP p1_paramSEXP, SEXP p2_typeSEXP, SEXP p2_paramSEXP, SEXP lam1_vecSEXP, SEXP lam2_vecSEXP, SEXP r2SEXP, SEXP r3SEXP, SEXP phiSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const char >::type p1_type(p1_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type p1_param(p1_paramSEXP);
    Rcpp::traits::input_parameter< const char >::type p2_type(p2_typeSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type p2_param(p2_paramSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type lam1_vec(lam1_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type lam2_vec(lam2_vecSEXP);
    Rcpp::traits::input_parameter< const double >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< const double >::type r3(r3SEXP);
    Rcpp::traits::input_parameter< const double >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(RSAVS_LargeN_L2_Rcpp(x_mat, y_vec, n, p, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r2, r3, phi, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// RSAVS_Solver_Cpp
Rcpp::List RSAVS_Solver_Cpp(const Eigen::VectorXd& y_vec, const Eigen::MatrixXd& x_mat, const int& n, const int& p, const std::string& l_type, const Eigen::VectorXd& l_param, const char& p1_type, const Eigen::VectorXd p1_param, const char& p2_type, const Eigen::VectorXd p2_param, const Eigen::VectorXd& const_r123, const Eigen::VectorXd& const_abc, const double& tol, const int& max_iter, const double& cd_tol, const int& cd_max_iter, const Rcpp::List& initial_values, const Rcpp::List& additional_values, const double& phi, const bool& loss_track, const bool& diff_update, const Eigen::VectorXd& omp_zsw, const int& eigen_pnum, const bool& s_v2);
RcppExport SEXP _RSAVS_RSAVS_Solver_Cpp(SEXP y_vecSEXP, SEXP x_matSEXP, SEXP nSEXP, SEXP pSEXP, SEXP l_typeSEXP, SEXP l_paramSEXP, SEXP p1_typeSEXP, SEXP p1_paramSEXP, SEXP p2_typeSEXP, SEXP p2_paramSEXP, SEXP const_r123SEXP, SEXP const_abcSEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP cd_tolSEXP, SEXP cd_max_iterSEXP, SEXP initial_valuesSEXP, SEXP additional_valuesSEXP, SEXP phiSEXP, SEXP loss_trackSEXP, SEXP diff_updateSEXP, SEXP omp_zswSEXP, SEXP eigen_pnumSEXP, SEXP s_v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x_mat(x_matSEXP);
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const int& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type l_type(l_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type l_param(l_paramSEXP);
    Rcpp::traits::input_parameter< const char& >::type p1_type(p1_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type p1_param(p1_paramSEXP);
    Rcpp::traits::input_parameter< const char& >::type p2_type(p2_typeSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd >::type p2_param(p2_paramSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type const_r123(const_r123SEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type const_abc(const_abcSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type cd_tol(cd_tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type cd_max_iter(cd_max_iterSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type additional_values(additional_valuesSEXP);
    Rcpp::traits::input_parameter< const double& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool& >::type loss_track(loss_trackSEXP);
    Rcpp::traits::input_parameter< const bool& >::type diff_update(diff_updateSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type omp_zsw(omp_zswSEXP);
    Rcpp::traits::input_parameter< const int& >::type eigen_pnum(eigen_pnumSEXP);
    Rcpp::traits::input_parameter< const bool& >::type s_v2(s_v2SEXP);
    rcpp_result_gen = Rcpp::wrap(RSAVS_Solver_Cpp(y_vec, x_mat, n, p, l_type, l_param, p1_type, p1_param, p2_type, p2_param, const_r123, const_abc, tol, max_iter, cd_tol, cd_max_iter, initial_values, additional_values, phi, loss_track, diff_update, omp_zsw, eigen_pnum, s_v2));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_hello_world
Eigen::MatrixXd rcppeigen_hello_world();
RcppExport SEXP _RSAVS_rcppeigen_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcppeigen_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_outerproduct
Eigen::MatrixXd rcppeigen_outerproduct(const Eigen::VectorXd& x);
RcppExport SEXP _RSAVS_rcppeigen_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_innerproduct
double rcppeigen_innerproduct(const Eigen::VectorXd& x);
RcppExport SEXP _RSAVS_rcppeigen_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_bothproducts
Rcpp::List rcppeigen_bothproducts(const Eigen::VectorXd& x);
RcppExport SEXP _RSAVS_rcppeigen_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RSAVS_RSAVS_LargeN_Rcpp", (DL_FUNC) &_RSAVS_RSAVS_LargeN_Rcpp, 18},
    {"_RSAVS_RSAVS_LargeN_L2_Rcpp", (DL_FUNC) &_RSAVS_RSAVS_LargeN_L2_Rcpp, 15},
    {"_RSAVS_RSAVS_Solver_Cpp", (DL_FUNC) &_RSAVS_RSAVS_Solver_Cpp, 24},
    {"_RSAVS_rcppeigen_hello_world", (DL_FUNC) &_RSAVS_rcppeigen_hello_world, 0},
    {"_RSAVS_rcppeigen_outerproduct", (DL_FUNC) &_RSAVS_rcppeigen_outerproduct, 1},
    {"_RSAVS_rcppeigen_innerproduct", (DL_FUNC) &_RSAVS_rcppeigen_innerproduct, 1},
    {"_RSAVS_rcppeigen_bothproducts", (DL_FUNC) &_RSAVS_rcppeigen_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_RSAVS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
