# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RSAVS_LargeN_Rcpp <- function(x_mat, y_vec, n, p, loss_type, loss_param, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r1, r2, r3, phi, tol, max_iter) {
    .Call('_RSAVS_RSAVS_LargeN_Rcpp', PACKAGE = 'RSAVS', x_mat, y_vec, n, p, loss_type, loss_param, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r1, r2, r3, phi, tol, max_iter)
}

RSAVS_LargeN_L2_Rcpp <- function(x_mat, y_vec, n, p, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r2, r3, phi, tol, max_iter) {
    .Call('_RSAVS_RSAVS_LargeN_L2_Rcpp', PACKAGE = 'RSAVS', x_mat, y_vec, n, p, p1_type, p1_param, p2_type, p2_param, lam1_vec, lam2_vec, r2, r3, phi, tol, max_iter)
}

rcppeigen_hello_world <- function() {
    .Call('_RSAVS_rcppeigen_hello_world', PACKAGE = 'RSAVS')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_RSAVS_rcppeigen_outerproduct', PACKAGE = 'RSAVS', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_RSAVS_rcppeigen_innerproduct', PACKAGE = 'RSAVS', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_RSAVS_rcppeigen_bothproducts', PACKAGE = 'RSAVS', x)
}

